upstream quokka_frontend {
  server frontend:5173;
}

upstream quokka_go {
  server go:8080;
}

server {
  listen 80;
  server_name _;

  client_max_body_size 50m;

  location /api/ {
    proxy_pass http://quokka_go;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /rails/active_storage/ {
    proxy_pass http://quokka_go;
    proxy_set_header Host $host;
  }

  location /ws/ {
    proxy_pass http://quokka_go;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }

  location /internal/ {
    proxy_pass http://quokka_go;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://quokka_frontend;
    proxy_set_header Host $host;
  }
}
